check for speedmgmt failure in build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,9 +1,11 @@
 #!/usr/bin/env bash
 
-set -e
-
 # generate the helm chart
 VERSION=$(speedmgmt generate helm)
+if [[ -z "$VERSION" ]];then
+  echo "It looks like you're missing a required binary.  This script is intended for Speedscale engineers.  Use the helm command to interact with charts."
+  exit 1
+fi
 
 # use the chart's README as this repo's README
 cp "${VERSION}/README.md" .
@@ -26,6 +28,7 @@ $ PACKAGE=speedscale-operator make prepare
 $ make validate
 $ # git commit and push one or more times
 $ make validate
+$ make clean
 $ submit PR
 "
 
